version: 1.0

jobs:
  build-and-deploy:
    machine:
     image: ubuntu-2204:current

    steps:
      - checkout
      - run:
          name: Build Docker image
          command: |
            docker build -t node-js-sample .

      - run:
          name: Test Docker container
          command: |
            docker run -d -p 3000:8080
            sleep 5
            curl --fail http://localhost:3000/ || (echo "Test Docker container failed" && exit 1)



workflows:
  say-hello-workflow:
    jobs:
      - build-and-deploy